# Generated by Django 4.2.3 on 2023-08-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_rename_is_developer_user_is_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('category', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'expensedetail',
            },
        ),
    ]
